name: Git Action Call
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      commitMessage:
        description: 'Name for the commit'
        required: true
        default: 'Auto commit'
        type: string
         
        
          
    
jobs:
    run-windows-script:
        runs-on: windows-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Run CMD script
            run: cmd /c ".github/workflows/CommitAndDeploy.cmd"
            env:
              COMMIT_NAME: ${{ github.event.inputs.commitMessage }}